"""empty message

Revision ID: d9ff08ff27e2
Revises: 9aa793c5fc76
Create Date: 2021-10-30 09:01:29.300569

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd9ff08ff27e2'
down_revision = '9aa793c5fc76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interface', sa.Column('amount_task_done', sa.Integer(), nullable=True))
    op.add_column('interface', sa.Column('amount_task_failed', sa.Integer(), nullable=True))
    op.drop_column('interface', 'consistency')
    op.drop_column('interface', 'b_param')
    op.drop_column('interface', 'a_param')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interface', sa.Column('a_param', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('interface', sa.Column('b_param', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('interface', sa.Column('consistency', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('interface', 'amount_task_failed')
    op.drop_column('interface', 'amount_task_done')
    # ### end Alembic commands ###
